### ISSUE TITLE
Change Margins and Font Size

### ISSUE THREAD

**Issue by songzee** [cczhong11/Resume-Generator#1]
Hi 

Could you please advise how to change Margins and Font size? Thanks

**Comment by cczhong11** [comment]
You could change font size here https://github.com/cczhong11/Resume-Generator/blob/8020a0fa0ed501ceb16ea5311d654a93f3710ad8/template/resume.cls#L3

And for margins, you could see each pre-defined commands in this file , like https://github.com/cczhong11/Resume-Generator/blob/8020a0fa0ed501ceb16ea5311d654a93f3710ad8/template/resume.cls#L63

**Comment by songzee** [comment]
Thanks！
